version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - C:/Users/ChenJiang/Desktop/agent/data:/data
    # - C:/Users/DELL/Desktop/data-agent/n8n_agent/data:/data
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_FEATURE_FLAGS=communityNodes,mcpBeta
